version: '3.8'

services:
  discord-bot:
    build: .
    container_name: frijolebot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      # WhatsApp session persistence
      - whatsapp-sessions:/app/auth_info_baileys
    environment:
      - NODE_ENV=production
      # Health check configuration
      - HEALTH_CHECK_PORT=3000
      # Rate limiting configuration (optional overrides)
      # - RATE_LIMIT_ENABLED=true
      # - RATE_LIMIT_WINDOW_MS=60000
      # - RATE_LIMIT_MAX_REQUESTS=5
      # - RATE_LIMIT_CLEANUP_INTERVAL=300000
    ports:
      # Expose health check port for monitoring
      - "3000:3000"
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health/live"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  bot-network:
    driver: bridge

volumes:
  logs:
  whatsapp-sessions:
